### ISSUE TITLE
Creating an Array containing the squares of another array in a non decreasing order

### ISSUE THREAD

**Issue by Garv085** [PEC-CSS/graveyard#10]
#DSA
Given a sorted array A containing N integers both positive and negative.
You need to create another array containing the squares of all the elements in A and return it in non- decreasing order.
Write a Python program to implement this in O(N) time.
Example Input
Input 1:
A = [-6, -3, -1, 2, 4, 5] 
Input 2:
A = [-5, -4, -2, 0, 1]
Example Output 
Output 1:
[1, 4, 9, 16, 25, 36] 
Output 2:
[0, 1, 4, 16, 25]

**Comment by ragss69** [comment]
Please assign this to me
