### ISSUE TITLE
Create a filtered dataframe

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/graveyard#107]
Use this dataframe
```py
df = pd.DataFrame({"name": ["pikachu", "charmander", "bulbasaur", "arceus", "mewtwo", "sceptile"], "happiness": [50, 99, 43, 0, 95, 69]})
```
Create a new dataframe from this dataframe having only those entries that have happiness >= 50
Do this without loop in one line, u can use inbuilt functions

**Comment by ItsPranavz** [comment]
Please assign this to me.
