### ISSUE TITLE
SORT the stack recursively in decreasing order

### ISSUE THREAD

**Issue by Garv085** [PEC-CSS/graveyard#11]
#DSA
Given a Stack 'S'. Write a Python Program to SORT the stack recursively in decreasing order. Note: Looping through stack is not allowed. You need to return a stack that is sorted in decreasing order.
Example:
Given stack: 
5 1 2 6 4 
Output:
6 5 4 2 1

**Comment by Abhishek-Sood** [comment]
please assign it to me

**Comment by AkankshaNarula** [comment]
Pls assign me this issue

**Comment by devikasood** [comment]
please assign this to me if it is available?
