### ISSUE TITLE
Merge Two Sorted Lists

### ISSUE THREAD

**Issue by Garv085** [PEC-CSS/graveyard#13]
You are given the heads of two sorted linked lists list1 and list2.
Merge the two lists in a one sorted list. The list should be made by splicing together the nodes of the first two lists.
Return the head of the merged linked list.

Example 1:
Input: list1 = [1,2,4], list2 = [1,3,4]
Output: [1,1,2,3,4,4]

**Comment by aadityasharma911** [comment]
please assign this to me

**Comment by hattymatty1** [comment]
Please assign this issue to me

**Comment by Modernbeast02** [comment]
@aadityasharma911  Good Luck!
