### ISSUE TITLE
Write a command line application in language of your choice for a TODO app

### ISSUE THREAD

**Issue by harshjohar** [PEC-CSS/graveyard#131]
It should have following methods
- create task
- show all tasks

BONUS: label a task and show tasks by labels 
> bonus can get you 2 points

**Comment by GauravGupta993** [comment]
Please assign this issue to me

**Comment by GauravGupta993** [comment]
is it fine to write code in python and then create a .exe file from it using pyinstaller? 
Or to create using argparser but then it would need to store data in .txt file as data would be lost once program is executed.

**Comment by Ishwarendra** [comment]
It's completely ok @GauravGupta993. You need not to worry about losing data after program closes.

**Comment by GauravGupta993** [comment]
Added Tags too.
![Windows PowerShell 05-03-2023 19_11_13](https://user-images.githubusercontent.com/123398315/222964152-a974905b-640f-4d70-95cf-a7bee91fa603.png)
