### ISSUE TITLE
Console application in CPP/JAVA

### ISSUE THREAD

**Issue by harshjohar** [PEC-CSS/graveyard#133]
Make a console application which has the following features

- date - Shows current date
- python - Execute a python file
- list - List current directory
- color - Changes text color
- ipc - Returns IP and HOSTNAME
- spec - System specifications
- gendir - Generate a new directory
- exit - Exits this program

User should have option to select the input.

**Comment by hattymatty1** [comment]
Please assign this issue to me >_<

**Comment by harshjohar** [comment]
@hattymatty1 any updates?

**Comment by ken1000minus7** [comment]
Unassigning due to inactivity

**Comment by AkankshaNarula** [comment]
pls assign me this issue
