### ISSUE TITLE
Longest Consecutive Sequence

### ISSUE THREAD

**Issue by iamakashrout** [PEC-CSS/graveyard#135]
### LONGEST CONSECUTIVE SEQUENCE

Given an unsorted array of integers **nums**, return the length of the **_longest consecutive elements sequence_**. In other words find the longest sequence of consecutive integers that can be formed by taking elements from the input array.

**Example 1:**
**Input:** nums = [100,4,200,1,3,2]
**Output:** 4
**Explanation:** The longest consecutive elements sequence is _[1, 2, 3, 4]_. Therefore its length is **4**.

**Example 2:**
**Input:** nums = [0,3,7,2,5,8,4,6,0,1]
**Output:** 9
**Explanation:** The longest consecutive elements sequence is _[0, 1, 2, 3, 4, 5, 6, 7, 8]_. Therefore its length is **9**.

**Expected Time Complexity:** O(n)
**Expected Space Complexity:** O(n)

**Hints:** Array, Sorting, Hash Table

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by Ishwarendra** [comment]
Your previous PRs are not merged yet @himanshusab12. Wait for them.

**Comment by AkankshaNarula** [comment]
Pls assign me this issue
