### ISSUE TITLE
Largest Number

### ISSUE THREAD

**Issue by iamakashrout** [PEC-CSS/graveyard#136]
### Largest Number

Given a list of non-negative integers **_nums_**, arrange them such that they form the **largest number** and return it.
Since the result may be very large, so you need to **return a string** instead of an integer.

**Example 1:**
**Input:** nums = [10,2]
**Output:** "210"
**Explanation:** Order of elements taken in the answer is 2, 10.

**Example 2:**
**Input:** nums = [3,30,34,5,9]
**Output:** "9534330"
**Explanation:** Order of elements taken in the answer is 9, 5, 34, 3, 30.

**Hints:** Array, String, Sorting

**Comment by ItsPranavz** [comment]
Please assign this to me.

**Comment by iamakashrout** [comment]
@ItsPranavz 

![Screenshot (157)](https://user-images.githubusercontent.com/116869015/222878873-e3d7a00b-4009-4a99-8506-612c6efddb9c.png)
Out should be 210

![Screenshot (158)](https://user-images.githubusercontent.com/116869015/222878884-672fd872-2b88-4381-8cd8-1e72e43645c3.png)
Output should be 9534330

Even in integer format the result is incorrect. Try to understand the problem properly and also look how to convert integers to string format.

**Comment by ItsPranavz** [comment]
Ok, understood. I apologize for not thoroughly understanding the statement before proceeding. I will correct the code as per your guidelines.
