### ISSUE TITLE
BMI Calculator

### ISSUE THREAD

**Issue by iamakashrout** [PEC-CSS/graveyard#138]
**BMI CALCULATOR**

Create a **Web Application** which takes in the **weight** and **height** as input from the user and **calculates and displays the BMI**.
BMI (Body Mass Index) is defined as the ratio of the weight (in kg) and square of the height (in sq. m).
**BMI=weight/(height)^2**

**Expected Functionality:**

![Screenshot (154)](https://user-images.githubusercontent.com/116869015/222877406-2a9b8413-f049-49e2-b45b-62597bf68dd5.png)
![Screenshot (155)](https://user-images.githubusercontent.com/116869015/222877416-745b713d-ef1f-4e18-bfcf-e5456a953ce4.png)
![Screenshot (156)](https://user-images.githubusercontent.com/116869015/222877423-a2c8014c-2aa9-44f7-81ec-e40c49eb6e31.png)

Use a form to take input from the user, calculate the BMI value and send it back to the user.

**Hints:** Node.js, Express.js

**Comment by AkankshaNarula** [comment]
Pls assign me this issue

**Comment by si-ddhant** [comment]
assigned @AkankshaNarula
