### ISSUE TITLE
Implement Binary Search

### ISSUE THREAD

**Issue by GeetanshuGarg39** [PEC-CSS/graveyard#14]
Given an array of integers 'nums' which is sorted in ascending order, and an integer target, write a function to search target in 'nums'. If target exists, then return its index. Otherwise, return -1.

You must write an algorithm with O(log n) runtime complexity.

Example 1:

Input: nums = [1,2,3,5,9,12], target = 3
Output: 2

Example 2:

Input: nums = [6,18,30,45], target = 9
Output: -1

**Comment by ItsPranavz** [comment]
Please assign this issue to me.

**Comment by ken1000minus7** [comment]
Work on one issue at a time :redeyes:

**Comment by ken1000minus7** [comment]
Reserved for rohan

**Comment by RohanMalik2710** [comment]
Please assign this issue to me !
