### ISSUE TITLE
Writing into file instead of directly printing

### ISSUE THREAD

**Issue by Ishwarendra** [PEC-CSS/graveyard#142]
# Miscellaneous

- Write a program which takes in two numbers as input and print their sum as output. 
- **But** instead of writing output to [`standard output`](https://www.computerhope.com/jargon/s/stdout.htm#:~:text=Stdout%2C%20also%20known%20as%20standard,defaults%20to%20the%20user's%20screen.) , you write it in a **text file** which has same name as your program.

More Details:
- Text file should not be created manually, instead your python program should create it.
- Text file and your python program should have same name. So if I change your python program name to `changed_name.py` and then run it the new Text file should have the name `changed_name.txt`. **NOTE** that you can choose any language other than python too for this.

**Comment by GauravGupta993** [comment]
please assign this issue to me

**Comment by GauravGupta993** [comment]
Please assign this issue to me.

**Comment by GauravGupta993** [comment]
Please assign this issue to me.

**Comment by ragss69** [comment]
Please assign this issue to me

**Comment by GauravGupta993** [comment]
Please assign this issue to me. The code is ready(It was written as a subpart of another issue.).

**Comment by Ishwarendra** [comment]
Finish your other issues first @GauravGupta993

**Comment by GauravGupta993** [comment]
I have created PR on both issues that I think will solve them. Please assign this issue to me.

**Comment by GauravGupta993** [comment]
> Finish your other issues first @GauravGupta993

Already created PR for both issues that I think will solve the issues but have not gotten any reply yet.
