### ISSUE TITLE
Replicate the design using tailwindcss

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/graveyard#143]
Replicate the design mentioned in #24 but use tailwindcss instead

**Comment by harshjohar** [comment]
No one taking this one, should I do this? :kek:

**Comment by ken1000minus7** [comment]
no lol :kek:

**Comment by ken1000minus7** [comment]
Nobun taking, arre 2nd year mei se hi lelo chahe koi, itna toh asan hai :crykek:

**Comment by harshjohar** [comment]
I was saying mujhe dedo :crycatok;

**Comment by ken1000minus7** [comment]
3rd year no :crycatok:

**Comment by RohanMalik2710** [comment]
**Please assign this issue to me**. I have already made a pull request for the issue previously assigned to me

**Comment by RohanMalik2710** [comment]
> **Please assign this issue to me**. I have already made a pull request for the issue previously assigned to me

.

**Comment by ItsPranavz** [comment]
If no one is doing this please assign this to me. Looks like a tough one!

**Comment by ken1000minus7** [comment]
@ItsPranavz any updates?

**Comment by ItsPranavz** [comment]
> @ItsPranavz any updates?

None, I am clueless and and I just won't get enough time to teach myself some css first because of the 8-5 clg grind.
