### ISSUE TITLE
Taking input from command line in Python

### ISSUE THREAD

**Issue by Ishwarendra** [PEC-CSS/graveyard#144]
# Miscellaneous

- Write a program in python which takes in a list of **positive numbers** from command line and then prints the maximum of them on screen.
- An image showing how to take input  
  <img width="311" alt="image" src="https://user-images.githubusercontent.com/75680424/222886506-c61e024c-0e70-4d7c-ada3-f792ce661549.png">
- Output of above image will be $8$.
- If no parameter is passed, i.e. I type only `py takeInputFromTerminal.py` then output should be $0$
 

<details>
<summary> Positive numbers? </summary>

A number $N$ is said to be positive integer iff $N \in [1, \infty)$ and $N \in \mathbb{Z}$, where $\mathbb{Z}$ is the set of integers.

</details>

Similar issue: #145

**Comment by SAHIL-KUMAR-EE** [comment]
Sir, Kindly assign this issue to me.

**Comment by Ishwarendra** [comment]
Assigned @SAHIL-KUMAR-EE
