### ISSUE TITLE
Taking input from command line in C++

### ISSUE THREAD

**Issue by Ishwarendra** [PEC-CSS/graveyard#145]
# Miscellaneous

- Write a program in C++ which takes in a list of **positive numbers** from command line and then prints the maximum of them on screen.
- An image showing how to take input  
   <img width="434" alt="image" src="https://user-images.githubusercontent.com/75680424/222886667-cd8fd92a-deb7-4f1d-9417-184e3b171392.png">
- Output of above image will be $8$.
- If no parameter is passed, i.e. I type only `./akeInputFromTerminal.exe` then output should be $0$.

<details>
<summary> Positive numbers? </summary>

A number $N$ is said to be positive integer iff $N \in [1, \infty)$ and $N \in \mathbb{Z}$, where $\mathbb{Z}$ is the set of integers.

</details>

**NOTE:** Taking input from command line and normally are different so don't write plain C++ code.
Similar issue: #144

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by Ishwarendra** [comment]
Assigned @himanshusab12
