### ISSUE TITLE
Use js to preview websites in iframe

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/graveyard#146]
Add buttons for different kind of websites like youtube, netflix etc whatever u want and below them display the corresponding website the user clicks on using iframe, like when i click on the youtube button , youtube website should be displayed below

**Comment by Dharya4242** [comment]
Please assign this issue to me.

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by ken1000minus7** [comment]
Complete the assigned issue first
