### ISSUE TITLE
Create a quiz using simple HTML and JS

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/graveyard#148]
Let's spice things up a bit

You need to create a quiz where there is a question and below it 4 radio buttons representing 4 options, the user will choose one option and then click on next button below the options to move to the next question (the user can't move to the next question until they select an option), after completing all questions display the score of the user

You can maintain information about every question as a list of js objects like this if u want
```js
let questions=[{
	question:"What is the capital of Turkey?",
	options:["Istanbul","Ankara","Jerusalem","Barbara"]
	answer: 1
},{
	question:"What is the capital of Israel?",
	options:["Istanbul","Ankara","Jerusalem","Barbara"],
	answer: 2
}]
```

**Comment by himanshusab12** [comment]
Please assign this question me

**Comment by GauravGupta993** [comment]
please assign this issue to me
