### ISSUE TITLE
Find X

### ISSUE THREAD

**Issue by sujal-aggarwal** [PEC-CSS/graveyard#149]
### Find X
<hr>

Find a number x such that x<sup>2</sup>+√x=c

**Input Format**

The input contains one real number c

**Constraints**

1.0≤c≤10<sup>10</sup>

**Output Format**

Print one number, the required x. The answer will be considered correct if the relative or absolute error is not more than 10<sup>-6</sup>

**Sample Input** 

10

**Sample Output** 

2.881410786256594303

**Comment by ItsPranavz** [comment]
Please assign this to me.

**Comment by Ishwarendra** [comment]
@ItsPranavz Fix your other PR before asking for new issue.

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by Ishwarendra** [comment]
Hey @himanshusab12, you have already got one issue

**Comment by ParasBisht2003** [comment]
please assign this issue to me
