### ISSUE TITLE
Choco Challenge 

### ISSUE THREAD

**Issue by YashitaBansal** [PEC-CSS/graveyard#15]
# CP
Marcus and Tessa are playing a game “_Choco Challenge_”. There are N boxes each having one or more chocolates. Boxes are numbered from 1 to N, where ith container has A[i] number of chocolates.
The game has following rules:
1. First player will choose a box and take one or more chocolates from it. 
2. Then, second player will choose a box and take one or more chocolates from it. 

They take alternate turns. This process will continue, until one of the players is not able to take any chocolates because no chocolates are left _:crycatok:_ One who is not able to take any chocolates loses the game. _Note that player can choose only non-empty box._
The game between Marcus and Tessa has just started, and Marcus has got the first Chance. He wants to know the number of ways to make a first move such that under optimal play, the first player always wins.

**Input Format**
The first line contains an integer N, i.e., number of boxes. The second line contains N integers, i.e., number of chocolates in each of the boxes separated by a single space.

**Constraints**
1 ≤ N ≤ 10<sup>6 </sup>
1 ≤ A[i] ≤ 10<sup>9 </sup>

**Output Format**
Print the number of ways to make the first move such that under optimal play, the first player always wins. If the first player cannot win under optimal play, print 0.

**Sample Input 1**

2
2 3

**Sample Output**

1

**Comment by Abhishek-Sood** [comment]
please assign it to me

**Comment by ken1000minus7** [comment]
Unassigning since u already hv one issue assigned

**Comment by Abhishek-Sood** [comment]
unaasign the rest plz assign this one to me please

**Comment by ken1000minus7** [comment]
Oki then
