### ISSUE TITLE
Find the winner

### ISSUE THREAD

**Issue by abhinavmalhotra01** [PEC-CSS/graveyard#151]
# CP

## Problem Statement 
One day,  Zoro decided to have a look at the scores of the finals of the PEC football tournament (only 2 teams can play finals 🤓) , but he is not good at maths and needs your help. You are provided with the count of the total number of goals made in the match and the name of the team that scored the corresponding goal. The team with the maximum number of goals will win. Kindly help Zoro 😇  

### Input Format -
First Line contains a single integer , the total number of goals in the match. The following n lines contain a string denoting the name of team that scored the ith goal. 

### Output Format - 
A string denoting the name of the winner team

### Constraints -
1<= n <= 100
1<= team_name.size() <= 10 (the size of the team name string will not exceed 10 and string will be in uppercase always)

### Example -
Input :
5
A
ABA
ABA
A
A

Output :
A

### Explanation -
Team with name 'A' scored 3 goals , whereas team with name 'ABA' scored 2 goals and hence , team 'A' was the winner

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by Prajwa-l-Kumar** [comment]
Please assign this issue to me
