### ISSUE TITLE
Return Minimum

### ISSUE THREAD

**Issue by Modernbeast02** [PEC-CSS/graveyard#154]
AquaMoon has a string 𝑎 consisting of only 0 and 1. She wants to add + and − between all pairs of consecutive positions to make the absolute value of the resulting expression as small as possible. Can you help her?

**INPUT**
The first line contains a single integer 𝑡 (1≤𝑡≤2000) – the number of test cases. The description of test cases follows.
The first line of each test case contains a single integer 𝑛 (2≤𝑛≤100) — the length of 𝑎.
The second line of each test case contains a string 𝑎 of length 𝑛, consisting of only 0 and 1.

**OUTPUT**
For each test case, output a string of length 𝑛−1 consisting of − and + on a separate line. If there is more than one assignment of signs that produces the smallest possible absolute value, any of them is accepted.

**Comment by aadityavvij** [comment]
Please assign this issue to me

**Comment by Modernbeast02** [comment]
> Please assign this issue to me

Complete previous assigned issues first 👿

**Comment by Prajwa-l-Kumar** [comment]
Please assign this issue to me
