### ISSUE TITLE
Ishwar loves Odd Numbers

### ISSUE THREAD

**Issue by Modernbeast02** [PEC-CSS/graveyard#155]
Today Ishwar came home from school with homework. In the assignment, Ishwar was given an array 𝑎 of length 𝑛. The task was to find 3 numbers in this array whose sum is odd. At school, he claimed that there are such 3 numbers, but Ishwar was not sure, so he asked you for help.
Answer if there are such three numbers, and if so, output indices 𝑖, 𝑗, and 𝑘 such that 𝑎𝑖 + 𝑎𝑗 + 𝑎𝑘 is odd.

**INPUT**
The first line contains a single integer 𝑡 (1≤𝑡≤104) — the number of test cases.
For each test case, the first line contains one integer 𝑛 (3≤𝑛≤300) — the length of 𝑎.
The second line contains 𝑛 integers 𝑎1,𝑎2,…,𝑎𝑛(1≤𝑎𝑖≤105) — the array 𝑎.

**OUTPUT**

For each test case, in the first line print one word "YES" (without quotes) if there are 3 numbers with an odd sum or "NO" (without quotes) if there are no such 3 numbers.
If the answer exists, then on the second line print 3 distinct integers 𝑖,𝑗,𝑘 (1 ≤ 𝑖, 𝑗, 𝑘 ≤ 𝑛) — the indices of the numbers. If there are several answers, output any.

**Sample Tests**
6
3
1 1 1
4
1 1 2 2
3
1 2 3
5
1 4 5 1 2
4
2 6 2 4
5
5 6 3 2 1

**OUTPUT**
YES
1 2 3
YES
3 4 1
NO
YES
1 3 4
NO
YES
1 3 5

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by Modernbeast02** [comment]
> Please assign this issue to me

Best of Luck
