### ISSUE TITLE
Integer Sequence Dividing

### ISSUE THREAD

**Issue by YashitaBansal** [PEC-CSS/graveyard#156]
You are given an integer sequence 1,2,…,𝑛
. You have to divide it into two sets **𝐴** and **𝐵**  in such a way that each element belongs to exactly one set and |𝑠𝑢𝑚(𝐴)−𝑠𝑢𝑚(𝐵)| is minimum possible.

The value _|𝑥|_ is the absolute value of 𝑥 and _𝑠𝑢𝑚(𝑆)_  is the sum of elements of the set 𝑆.

**Input**
The first line of the input contains one integer 𝑛 (1 ≤ 𝑛 ≤ 2⋅10<sup>9</sup>).

**Output**
Print one integer — the minimum possible value of _|𝑠𝑢𝑚(𝐴)−𝑠𝑢𝑚(𝐵)|_ if you divide the initial sequence $1,2,…,𝑛$ into two sets _𝐴_ and _𝐵_.

**Sample Test Case**
   3
 **Output** 
  0

**Comment by Knight-Fenris** [comment]
Please assign this issue to me
