### ISSUE TITLE
Carl's Training

### ISSUE THREAD

**Issue by YashitaBansal** [PEC-CSS/graveyard#157]
Carl wants to train before another programming competition. During the first day of his training he should solve exactly $1$ problem, during the second day — exactly $2$ problems, during the third day — exactly $3$ problems, and so on. During the 𝑘-th day he should solve 𝑘 problems.

Polycarp has a list of 𝑛 contests, the 𝑖-th contest consists of 𝑎𝑖 problems. During each day Polycarp has to choose exactly one of the contests he didn't solve yet and solve it. He solves exactly 𝑘 problems from this contest. Other problems are discarded from it. If there are no contests consisting of at least 𝑘 problems that Polycarp didn't solve yet during the 𝑘 -th day, then Polycarp stops his training.

How many days Polycarp can train if he chooses the contests optimally?

**Input**
The first line of the input contains one integer 𝑛 (1 ≤ 𝑛 ≤ 2⋅10<sup>5</sup>) — the number of contests.
The second line of the input contains 𝑛 integers $𝑎1,𝑎2,…,𝑎𝑛$ (1 ≤ 𝑎𝑖 ≤ 2⋅10<sup>5</sup>) — the number of problems in the 𝑖-th contest.

**Output**
Print one integer — the maximum number of days Polycarp can train if he chooses the contests optimally.

**Sample Test Case**
4
3 1 4 1

**Output**
3

**Comment by Prajwa-l-Kumar** [comment]
Please assign this issue to me
