### ISSUE TITLE
Find Percentile

### ISSUE THREAD

**Issue by iamakashrout** [PEC-CSS/graveyard#158]
### **FIND PERCENTILE OF DATA**

Given an 2-D array **_arr_** of size **_m X n_** and an integer _**p**_ lying between 0 and 100 (both inclusive), find:

- The **pth percentile** value of the **flattened array**.
- The **pth percentile** values of **each row**.
- The **pth percentile** values of **each column**.

The **pth percentile** of a dataset gives a number which is **greater than the values of p% elements** of that dataset.

**Example:**
**Input:**
m=3, n=5, p=50
arr=[[3, 8, 1, 4, 6], [1, 7, 4, 6, 12], [[14, 1, 16, 9, 6]]
**Output:**
50th percentile of flattened array is 6.0.
50th percentile values of rows are [4. 6. 9.]
50th percentile values of columns are [3. 7. 4. 6. 6.]

**Hint:** Numpy

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by YashitaBansal** [comment]
> Please assign this issue to me

Complete previous assigned issues first.

**Comment by himanshusab12** [comment]
Already completed the previous problem and that has already been merged into main by Ishwarendra sir.
So, please assign this issue to me.

**Comment by iamakashrout** [comment]
assigned @himanshusab12, good luck!
