### ISSUE TITLE
Print pattern

### ISSUE THREAD

**Issue by GeetanshuGarg39** [PEC-CSS/graveyard#16]
Print the given pattern
![image](https://user-images.githubusercontent.com/118442949/221375058-4d687ee7-10fc-4d60-b24c-6040bd16843e.png)

**Comment by ItsPranavz** [comment]
Please assign this issue to me.

**Comment by Aanya0809** [comment]
please assign this issue to me.

**Comment by Dharya4242** [comment]
Please assign this issue to me.
