### ISSUE TITLE
Longest Substring

### ISSUE THREAD

**Issue by sujal-aggarwal** [PEC-CSS/graveyard#160]
### CP
<hr>

Given a string `s` consisting of lowercase letters, 
find the length of the longest substring that contains at most `k` distinct characters.

**Input Format**

`s`  a string where 1 <= len(s) <= 10<sup>4</sup>
`k`  an integer where 1 <= k <= 26

**Output Format**

Print an integer representing the length of the longest substring that contains at most k distinct characters.

Sample Test Case

**Input**
aabbbc
2
**Output**
5
**Explaination**

<i>In the above test case the longest substring containing at most 2 distinct characters is </i>`aabbb` <i> , containing only 2 distinct characters </i> `a` and `b` , <i>having a total length of 5</i>

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by ragss69** [comment]
Please assign this issue to me

**Comment by AkshatKesari** [comment]
Please assign this issue to me

**Comment by abhinavmalhotra01** [comment]
> Please assign this issue to me

You already have 3 issues assigned to you

**Comment by abhinavmalhotra01** [comment]
> Please assign this issue to me

Sorry vro, first come first serve basis , you can check some other cp related issue
