### ISSUE TITLE
IPL Teams

### ISSUE THREAD

**Issue by iamakashrout** [PEC-CSS/graveyard#162]
### **IPL TEAMS**

Create an HTML Page displaying a **table containing the list of all 10 IPL teams** (in alphabetical order). The table should consist:

- A **heading** having text **_'IPL TEAMS'_** in stylized text.
- **3 Columns** representing **serial number, team name and team logo**.
-  **Label** of each column.
- The **team name field should be clickable** and should load the Wikipedia page of the team on clicking.
- Proper **styling and sizing** of all text and images.

**Reference:** https://en.wikipedia.org/wiki/Indian_Premier_League#Teams

**Hint:** HTML, CSS

**Comment by AkankshaNarula** [comment]
Pls assign me this issue

**Comment by Dharya4242** [comment]
please assign this issue to me.

**Comment by iamakashrout** [comment]
assigned @Dharyaj11
@AkankshaNarula , please complete the previously assigned issues first
