### ISSUE TITLE
Scatter Plots

### ISSUE THREAD

**Issue by iamakashrout** [PEC-CSS/graveyard#168]
### **SCATTER PLOTS**

There are two car manufacturers **A** and **B**. Arrays **_ageA_** and **_speedA_** represent the ages (in years) and maximum speeds (in km/h) of a set cars of manufacturer A and **_ageB_** and **_speedB_** represent that of manufacturer B. Draw the **speed (on y-axis) vs age (on x-axis) scatter plots** of both the manufacturers on the **same graph**.

**Example:**
**Input:**
ageA = [5, 7, 8, 7, 2, 17, 2, 9, 4, 11, 12, 9, 6]
speedA = [99, 86, 87, 88, 111, 86, 103, 87, 94, 78, 77, 85, 86]
ageB = [2, 2, 8, 1, 15, 8, 12, 9, 7, 3, 11, 4, 7, 14, 12]
speedB = [100, 105, 84, 105, 90, 99, 90, 95, 94, 100, 79, 112, 91, 80, 85]

**Output:**
![Screenshot (159)](https://user-images.githubusercontent.com/116869015/222916700-2fb07bc4-1ad5-4a15-96e1-ee7196fcfe30.png)
Here, points in blue represent Manufacturer A  and points in yellow represent Manufacturer B.

**Hints:** Matplotlib, Numpy

**Comment by Abhishek-Sood** [comment]
Assign this to me
