### ISSUE TITLE
Nobody Likes To Divide

### ISSUE THREAD

**Issue by Modernbeast02** [PEC-CSS/graveyard#176]
You are given an array of 𝑛 positive integers 𝑎1,𝑎2,…,𝑎𝑛. In one operation, you can choose any number of the array and add 1 to it.
Make at most 2𝑛 operations so that the array satisfies the following property: $a_i + 1$ is not divisible by $a_i$, for each 𝑖=1,2,…,𝑛−1.
You do not need to minimize the number of operations.

**INPUT**
The first line contains an integer 𝑛 (1≤𝑛≤ $10^4$) — the length of the given array.
The second line contains 𝑛  integers 𝑎1,𝑎2,…,𝑎𝑛 (1≤ $a_i$ ≤ $10^9$) — the given array.

**OUTPUT**
print 𝑛 integers — the resulting array 𝑎 after applying at most 2𝑛 operations.

**SAMPLE INPUT**
4
2 4 3 6
**SAMPLE OUTPUT**
4 5 6 7

**Explanation**
the array [4,5,6,7] can be achieved by applying 2 operations to the first element, 1 operation to the second element, 3 operations to the third element, and 1 operation to the last element. The total number of operations performed is 7, which is less than the allowed 8 operations in this case.

**Comment by himanshusab12** [comment]
Please assign this issue to me
