### ISSUE TITLE
Split NumPy Array

### ISSUE THREAD

**Issue by anshRS** [PEC-CSS/graveyard#18]
Write a NumPy program to split an array of shape 5x4 into two arrays such that first array contains first column entries and second array contains remaining column entries

_**Implement this in a ipynb**_

**Example: 
Original Array:** 
[[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19]]

**Output:**
**Array1**
[[ 0], [ 4], [ 8], [12], [16]]

**Array2**
[[ 1,  2,  3],
  [ 5,  6,  7],
  [ 9, 10, 11],
  [13, 14, 15],
  [17, 18, 19]]

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by ziqIshika0503** [comment]
please assign this issue to me

**Comment by harshjohar** [comment]
good luck @ziqIshika0503
