### ISSUE TITLE
Save Energy

### ISSUE THREAD

**Issue by Modernbeast02** [PEC-CSS/graveyard#184]
Stanley and Megan decided to shop in the "Crossmarket" grocery store, which can be represented as a matrix with 𝑛
 rows and 𝑚 columns.
Stanley and Megan can move to an adjacent cell using 1 unit of power. Two cells are considered adjacent if they share an edge. To speed up the shopping process, Megan brought her portals with her, and she leaves one in each cell she visits (if there is no portal yet). If a person (Stanley or Megan) is in a cell with a portal, that person can use 1 unit of power to teleport to any other cell with a portal, including Megan's starting cell.

They decided to split up: Stanley will go from the upper-left cell (cell with coordinates (1,1)) to the lower-right cell (cell with coordinates (𝑛,𝑚)), whilst Megan needs to get from the lower-left cell (cell with coordinates (𝑛,1)) to the upper-right cell (cell with coordinates (1,𝑚)).

What is the minimum total energy needed for them both to do that?
Note that they can choose the time they move. Time does not affect energy.

**INPUT**
Each test contains multiple test cases. The first line contains the number of test cases 𝑡 (1≤𝑡≤1000). A description of the test cases follows. The only line in the test case contains two integers 𝑛 and 𝑚 (1≤𝑛, 𝑚≤ $10^5$).

**OUTPUT**
For each test case print a single integer on a new line – the answer.

**SAMPLE**
7
7 5
5 7
1 1
100000 100000
57 228
1 5
5 1

**OUTPUT**
15
15
0
299998
340
5
5

**Comment by Abhishek-Sood** [comment]
pls assign it to me

**Comment by Abhishek-Sood** [comment]
sirr?

**Comment by krittika2004** [comment]
please assign this issue to me

**Comment by ken1000minus7** [comment]
Will assign to u @krittika2004 once u resolve the problems in your current pr

**Comment by krittika2004** [comment]
> Will assign to u @krittika2004 once u resolve the problems in your current pr

now pls assign

**Comment by ken1000minus7** [comment]
@krittika2004 any updates?
