### ISSUE TITLE
XOR IT UP

### ISSUE THREAD

**Issue by Modernbeast02** [PEC-CSS/graveyard#185]
There is an array 𝑎 with 𝑛−1 integers. Let 𝑥 be the [bitwise XOR](https://en.wikipedia.org/wiki/Bitwise_operation#XOR) of all elements of the array. The number 𝑥 is added to the end of the array 𝑎(now it has length 𝑛), and then the elements are shuffled.

You are given the newly formed array 𝑎. What is 𝑥? If there are multiple possible values of 𝑥, you can output any of them.

**Input**
The input consists of multiple test cases. The first line contains an integer 𝑡 (1≤𝑡≤1000) — the number of test cases. The description of the test cases follows.
The first line of each test case contains an integer 𝑛 (2≤𝑛≤100) — the number of integers in the resulting array 𝑎.

The second line of each test case contains 𝑛 integers 𝑎1,𝑎2,…,𝑎𝑛 (0 ≤ 𝑎𝑖 ≤ 127) — the elements of the newly formed array 𝑎.

An additional constraint on the input: the array 𝑎 is made by the process described in the statement; that is, some value of 𝑥 exists.

**Output**
For each test case, output a single integer — the value of 𝑥, as described in the statement. 
If there are multiple possible values of 𝑥, output any of them.

**SAMPLE**
4
4
4 3 2 5
5
6 1 10 7 10
6
6 6 6 6 6 6
3
100 100 0

**OUTPUT**
3
7
6
0

**Comment by GauravGupta993** [comment]
please assign this issue to me. I have already created PR for all current issues that are assigned to me that I think will solve the issue.
