### ISSUE TITLE
Fedya and Array

### ISSUE THREAD

**Issue by SUGAM-ARORA** [PEC-CSS/graveyard#188]
For his birthday recently Fedya was given an array a of n  integers arranged in a circle, For each pair of neighboring numbers (a1
 and a2 , a2  and a3 , …, an−1 and an, an and a1) the absolute difference between them is equal to 1.

Let's call a local maximum an element, which is greater than both of its neighboring elements. Also call a local minimum an element, which is less than both of its neighboring elements. Note, that elements a1  and an are neighboring elements.

Unfortunately, Fedya lost an array, but he remembered in it the sum of local maximums x and the sum of local minimums y
.
Given x  and y , help Fedya find any matching array of minimum length.

Input
Each test contains multiple test cases. The first line contains the number of test cases t
 (1≤t≤1000
). Description of the test cases follows.

Each line of each test case contain two integers x
 and y
 (−109≤y<x≤109
) — the sum of local maximums and the sum of local minimums, respectively.

Output
For each test case, in the first line print one integer n
 — the minimum length of matching arrays.

In the second line print n
 integers a1,a2,…,an
 (−109⩽ai⩽109
) — the array elements such that the the absolute difference between each pair of neighboring is equal to 1
.

If there are multiple solutions, print any of them.

It is guaranteed that the sum of n
 over all test cases does not exceed 2⋅105
.

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by ken1000minus7** [comment]
Resolve the issues in your current pr, before working on new issues

**Comment by aadityavvij** [comment]
Please assign this issue to me

**Comment by ken1000minus7** [comment]
@aadityavvij any updates?

**Comment by SUGAM-ARORA** [comment]
https://codeforces.com/contest/1793/submission/193369897
 Look this solution . 
Now I am closing the issue
