### ISSUE TITLE
PWOC OP

### ISSUE THREAD

**Issue by Modernbeast02** [PEC-CSS/graveyard#19]
# CP
Alice and Bob have been competitors for a long time. Now they have decided to compete in the PEC Winter Of Code (PWOC). Obviously, both of them want to win PWOC and get the prize money. To win, they both must get the maximum points possible. The person with higher points will win PWOC. 

There are $3$ types of problems available in PWOC. They are easy, medium, and hard. Easy questions will provide $2$ points, medium questions will provide $4$ points and hard problems will provide $6$ points. They will pick the questions one by one. A coin will be tossed to decide which player will pick the questions first.  If the coins show 'Tails', Alice will choose the question first otherwise Bob will choose first. They both will have alternate turns.

---

**Input Format**
The first line contains an integer N, the number of problems. The second line contains the output of coin, 'H' means head and 'T' means tails. The third line contain N characters E, M, H, where E refers to Easy question, M refers to medium question and H refers to hard question.

**Output Format**
Print "Alice" if Alice wins otherwise print "Bob".

**Sample Input 1**
5
T
H E M H M

**Sample Output**
Alice

**Comment by GauravGupta993** [comment]
Please assign this issue to me

**Comment by Modernbeast02** [comment]
This code is failing on the test case-
5
T
E H E H E

Your Output - Bob
Correct Answer - Alice.

If you don't understand why the Correct answer is Alice, u can ping me on discord.

**Comment by GauravGupta993** [comment]
Sir, i am unable to understand why alice is correct answer. I also do not know your discord username

**Comment by GauravGupta993** [comment]
> This code is failing on the test case- 5 T E H E H E
> 
> Your Output - Bob Correct Answer - Alice.
> 
> If you don't understand why the Correct answer is Alice, u can ping me on discord.

Sir, i am unable to understand why alice is correct answer. I also do not know your discord username
