### ISSUE TITLE
Titanic passengers

### ISSUE THREAD

**Issue by SUGAM-ARORA** [PEC-CSS/graveyard#194]
### ML
------------------------------
You want to plot histogram of age distribution for Titanic passengers, separate for males and females.

A)What are the relevant variable names?
B)How will you select the relevant columns?

Use pandas functions if applicable !!

Kaggle dataset 
-----------
https://www.kaggle.com/c/titanic/data

**Comment by Knight-Fenris** [comment]
Assign pls

**Comment by ken1000minus7** [comment]
Sure, gl

**Comment by ken1000minus7** [comment]
@Knight-Fenris any updates?

**Comment by Knight-Fenris** [comment]
> @Knight-Fenris any updates?

pr'd
