### ISSUE TITLE
Categorial data

### ISSUE THREAD

**Issue by SUGAM-ARORA** [PEC-CSS/graveyard#195]
Using dataset 
Convert age into three categories: 0-13, 14-50, 50- 

[titanic.csv](https://github.com/PEC-CSS/graveyard/files/10901874/titanic.csv)

**Comment by RohanMalik2710** [comment]
Please assign this issue to me

**Comment by ken1000minus7** [comment]
You have unresolved prs, resolve them first

**Comment by RohanMalik2710** [comment]
> You have unresolved prs, resolve them first

I have resolved it now and submitted a new commit in the same pr. It should work now. _Please assign this issue to me now_

**Comment by ken1000minus7** [comment]
Please check ur pr again, there still r pending changes to be resolved

**Comment by RohanMalik2710** [comment]
> Please check ur pr again, there still r pending changes to be resolved
I think they are resolved now in the new pr. Please check

**Comment by RohanMalik2710** [comment]
Please assign this issue to me
