### ISSUE TITLE
Boolean indexing

### ISSUE THREAD

**Issue by SUGAM-ARORA** [PEC-CSS/graveyard#196]
ML
------------------------------

Consider these two vectors :

names = np.array(["Roxana", "Statira", "Roxana", "Statira", "Roxana"])
score = np.array([126, 115, 130, 141, 132])

Do the following using a single one-line vectorized operation.

(a)Extract all test scores that are smaller than 130
(b)Extract all test scores by Statira
(c)Add 10 points to Roxana’s scores. (You need to extract it first.)

**Comment by Abhishek-Sood** [comment]
pls assign it to me

**Comment by AkankshaNarula** [comment]
Pls assign me this issue

**Comment by thapliyalaryan003** [comment]
> Please assign this issue to me
> 

Sir please assign to someone so that rest of us could ask different issues to be assigned.

**Comment by ken1000minus7** [comment]
Assigning to @Abhishek-Sood
