### ISSUE TITLE
Embedding vectors

### ISSUE THREAD

**Issue by SUGAM-ARORA** [PEC-CSS/graveyard#197]
### ML 

----------------------------

</html>
</body>

<body>

Word embeddings are low-dimensional vectors to describe human words. These are computed based on words’ co-occurrence in texts. As similar words tend to occur in similar contexts, they tend to have similar embedding vectors. Interestingly, one can also do certain mathematical operations with embedding vectors

Below is the first five components (out of 100) for Berlin, Germany, France, and Paris (based on Stanford’s [glove.twitter.27B.100d.txt](https://nlp.stanford.edu/projects/glove/)):
<html>

word | 1 | 2 | 3 | 4 | 5
-- | -- | -- | -- | -- | --
Berlin | -0.562 | 0.630 | -0.453 | -0.299 | -0.006
Germany | 0.194 | 0.507 | 0.287 | 0.132 | -0.281
France | 0.605 | -0.678 | -0.436 | -0.019 | -0.291
Paris | -0.074 | -0.855 | -0.689 | -0.057 | -0.139

Q ) Compute Berlin - Germany + France. How close do you get to Paris? (Compute the difference between the expression and Paris).

**Comment by GauravGupta993** [comment]
please assign this issue to me.

**Comment by ken1000minus7** [comment]
You have pending issues, complete them first

**Comment by Abhishek-Sood** [comment]
please assign this to me if no one working :)
