### ISSUE TITLE
Merging 2 datasets

### ISSUE THREAD

**Issue by sparsh44** [PEC-CSS/graveyard#199]
[Country-Code.xlsx](https://github.com/PEC-CSS/graveyard/files/10901976/Country-Code.xlsx)
[zomato.csv](https://github.com/PEC-CSS/graveyard/files/10901979/zomato.csv)

Your task is to observe the columns in both the datasets and make a common dataframe from them.
Hint/Learning : Go through joins in SQL tables ,  you will see a little correlation with this problem

Note : make sure that there is no repetition of data/no redundancy

**Comment by ItsPranavz** [comment]
Please assign this to me.

**Comment by Ishwarendra** [comment]
@ItsPranavz Fix your other PR before.

**Comment by ItsPranavz** [comment]
@Ishwarendra Done! Please check.

**Comment by ItsPranavz** [comment]
I think the PR wasnt linked to the issue because its still showing in the issues tab.
