### ISSUE TITLE
Create a 4x3 integer array

### ISSUE THREAD

**Issue by DhruvGoyal375** [PEC-CSS/graveyard#2]
# ml
Create a 4x3 integer array from a range between 10 to 33 such that the difference between each element is 2
Expected Output -
[[10 12 14]
[16 18 20]
[22 24 26]
[28 30 32]]

**Comment by aadityavvij** [comment]
Please assign this to me

**Comment by harshjohar** [comment]
@DhruvGoyal375 check the pr

**Comment by DhruvGoyal375** [comment]
## you can also use - 
import numpy as np
mat = np.arange(10, 33, 2).reshape(4, 3)     # only difference is that you can directly specify the increment value (2) instead of using number of steps (12) in linspace

**Comment by aadityavvij** [comment]
Ok, got it, do i need to change it?
