### ISSUE TITLE
Check If N and Its Double Exist

### ISSUE THREAD

**Issue by Clucthe** [PEC-CSS/graveyard#20]
# DSA
Given an array arr of integers, check if there exist two indices i and j such that :

i != j
0 <= i, j < arr.length
arr[i] == 2 * arr[j]
 

Example 1:

Input: arr = [10,2,5,3]
Output: true
Explanation: For i = 0 and j = 2, arr[i] == 10 == 2 * 5 == 2 * arr[j]
Example 2:

Input: arr = [3,1,7,11]
Output: false
Explanation: There is no i and j that satisfy the conditions.
 

Constraints:

1.  2 <= arr.length <= 500
2.  -103 <= arr[i] <= 103

**Comment by ragss69** [comment]
Please assign this to me

**Comment by ken1000minus7** [comment]
Work on one issue at a time :redeyes;

**Comment by Prakul06** [comment]
Please assign this to me.

**Comment by harshjohar** [comment]
@Clucthe check pr
