### ISSUE TITLE
North Indian Cuisine

### ISSUE THREAD

**Issue by sparsh44** [PEC-CSS/graveyard#200]
[Country-Code.xlsx](https://github.com/PEC-CSS/graveyard/files/10902062/Country-Code.xlsx)
[zomato.csv](https://github.com/PEC-CSS/graveyard/files/10902063/zomato.csv)

Return list of all the restaurants in a.) India b.) New Delhi which serve "North Indian" Cuisine

Hint : 1.) Refer to issue #199  2.)String matching

**Comment by ItsPranavz** [comment]
Please assign this to me.
