### ISSUE TITLE
Euclidean distance between 2 arrays

### ISSUE THREAD

**Issue by abhinavmalhotra01** [PEC-CSS/graveyard#201]
# ML

### Explanation :
Given 2 numpy arrays , you need to output a `float` value , the euclidean distance between the arrays ; 

### Example :
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,5,6,7,8])

output : 6.708 

### Explanation :
output = sqrt ( (4-1)^2 + (5-2)^2 + (6-3)^2 + (7-4)^2 + (8-5)^2  ) = sqrt ( 45 ) = 6.708

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by abhinavmalhotra01** [comment]
> Please assign this issue to me

vro i commented on your earlier pr , will assign you this issue , after it gets merged

**Comment by thapliyalaryan003** [comment]
Please assign this to me.

**Comment by thapliyalaryan003** [comment]
Sir do I need to fork again and delete old fork or work with old forked repository?

**Comment by abhinavmalhotra01** [comment]
> Sir do I need to fork again and delete old fork or work with old forked repository?

just create a new branch , no need to fork again , though you may sync your old fork with the current graveyard

**Comment by thapliyalaryan003** [comment]
New branch means new file under ML?

**Comment by abhinavmalhotra01** [comment]
> New branch means new file under ML?

first create branch , then add files in that branch
if you use terminal , you can do the following :
` git checkout -b branch_name `
then you can simply start adding files ,

if you use github desktop , find a button of creating new branch 👍

**Comment by abhinavmalhotra01** [comment]
if your earliear pr is merged , you can continue in same branch as well , 🤔

**Comment by thapliyalaryan003** [comment]
Sir please revert back I have sent pull request 2 days ago. If any errors please tell me.

**Comment by abhinavmalhotra01** [comment]
create new pr

**Comment by ken1000minus7** [comment]
You need to make a pr again

**Comment by abhinavmalhotra01** [comment]
> You need to make a pr again

sir #222 ke baad , dobara new ?

**Comment by ken1000minus7** [comment]
Oh pr is closed, issue close kardiya karo agar pr merge kardi hai

**Comment by abhinavmalhotra01** [comment]
> Oh pr is closed, issue close kardiya karo agar pr merge kardi hai

ohk sir , will take care next time
