### ISSUE TITLE
Handling Missing Values

### ISSUE THREAD

**Issue by iamakashrout** [PEC-CSS/graveyard#203]
### **HANDLING MISSING VALUES**

You are given the following dataset:

![Screenshot (160)](https://user-images.githubusercontent.com/116869015/223490535-e0dd98d7-e673-4750-9693-af2584588076.png)

Here, **_NaN (Not a Number)_** represents that the particular value is **missing** in the dataset.

**Find:**
- The total number of **missing values**.
- The **indices** of missing values in each column

**Then replace all the missing values by:**
- **Mean** of respective column.
- **Median** of respective column.
- **Most frequent value** of respective column.

**Hints:** Pandas

**Comment by AkankshaNarula** [comment]
Pls assign me this issue

**Comment by iamakashrout** [comment]
assigned @AkankshaNarula, good luck!

**Comment by AkankshaNarula** [comment]
@iamakashrout Also do we need to do this in jupyter notebook and then attach screenshot?

**Comment by iamakashrout** [comment]
you can add screenshot if you wish to
