### ISSUE TITLE
Hamburger Menu

### ISSUE THREAD

**Issue by iamakashrout** [PEC-CSS/graveyard#204]
### **HAMBURGER MENU**

Create a webpage with a navigation bar containing a **_hamburger menu_**. A **_hamburger menu_** (with three bars icon) displays the contents of the menu on clicking and rolls them back on clicking again.

**Example:**

![Screenshot (161)](https://user-images.githubusercontent.com/116869015/223496186-ad6dd253-58e8-4560-8134-ae1cfc428cf4.png)

On **clicking the three bars icon**, options of the menu should **load/disappear**.

![Screenshot (162)](https://user-images.githubusercontent.com/116869015/223496213-5bb73844-c0ff-45ec-9548-67d65a0a200d.png)

**Hint:** JavaScript

**Comment by AkankshaNarula** [comment]
Please assign me this issue

**Comment by iamakashrout** [comment]
assigned @AkankshaNarula, all the best!

**Comment by ken1000minus7** [comment]
@AkankshaNarula any updates?

**Comment by AkankshaNarula** [comment]
@ken1000minus7 will complete this surely by tom morning

**Comment by ken1000minus7** [comment]
Oki then, gl
