### ISSUE TITLE
Merge Intervals

### ISSUE THREAD

**Issue by iamakashrout** [PEC-CSS/graveyard#205]
### **MERGE INTERVALS**

Given an array of **_intervals_** where **_intervals[i] = [start(i), end(i)]_**, **merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input**.

**Example 1:**
**Input:** intervals = [[1, 3], [2, 6], [8, 10], [15, 18]]
**Output:** [[1, 6], [8, 10], [15, 18]]
**Explanation:** Since intervals [1, 3] and [2, 6] overlap, merge them into [1, 6].

**Example 2:**
**Input:** intervals = [[1, 4], [4, 5]]
**Output:** [[1, 5]]
**Explanation:** Intervals [1, 4] and [4, 5] are considered overlapping.

**Hints:** Array, Sorting

**Comment by Abhishek-Sood** [comment]
pls assign it to me

**Comment by iamakashrout** [comment]
assigned @Abhishek-Sood

**Comment by iamakashrout** [comment]
good work @Abhishek-Sood
