### ISSUE TITLE
Print All Codes

### ISSUE THREAD

**Issue by iamakashrout** [PEC-CSS/graveyard#206]
### **PRINT ALL CODES**

Assume that the value of **a = 1, b = 2, c = 3, . . . , z = 26**. You are given a **numeric string** **_S_**. Write a program to print the list of all possible codes that can be generated from the given string.

**Example 1:**
**Input:** s="1123"
**Output:**
aabc
kbc
alc
aaw
kw
**Explanation:**
1->a, 1->a, 2->b, 3->c
11->k, 2->b, 3->c
1->a, 12->l, 3->c
1->a, 1->a, 23->w
11->k, 23->w

**Example 2:**
**Input:** s="35411"
**Output:**
cedaa
cedk
**Explanation:**
3->c, 5->e, 4->d, 1->a, 1->a
3->c, 5->e, 4->d, 11->k

**Hints:** String, Recursion

**Comment by ragss69** [comment]
Please assign this issue to me
