### ISSUE TITLE
Stopwatch

### ISSUE THREAD

**Issue by iamakashrout** [PEC-CSS/graveyard#207]
### **STOPWATCH**

Create a **stopwatch application** with options to:
- **Start** timekeeping on it.
- **Stop** it at the current time.
- **Reset** it to 0.

The stopwatch should display the time since start in **_seconds : milliseconds_** format.

**Example:**

![Screenshot (163)](https://user-images.githubusercontent.com/116869015/223509595-f0a6ecff-eb1b-4504-a883-464faa7ba208.png)

**Hints:** JavaScript

**Comment by RohanMalik2710** [comment]
Please assign this issue to me

**Comment by thapliyalaryan003** [comment]
Please assign this to me .(can I use tkinter)

**Comment by ken1000minus7** [comment]
No, this is a issue specific for web, should I assign you?

**Comment by RohanMalik2710** [comment]
If no one else is in for it, please assign this issue to me. I have already made a pull request for the issue previously assigned to me.

~regards

**Comment by thapliyalaryan003** [comment]
> No, this is a issue specific for web, should I assign you?

I will be learning html and javascript, if more issues are yet to come please assign to someone else ,else assign to me.

**Comment by ken1000minus7** [comment]
Well, the event's gonna end in around 4 days so if u can complete it within that time, I'll assign it to you, lemme know if u can, for now i m assigning @RohanMalik2710
