### ISSUE TITLE
Simple Linear Regression

### ISSUE THREAD

**Issue by iamakashrout** [PEC-CSS/graveyard#208]
### **SIMPLE LINEAR REGRESSION**

Given a set of data points representing values of a **dependent variable _Y_** at any **independent variable _X_**, create a **linear relationship** between X and Y consisting of a slope and an intercept **(Y=mX+c)**. Find the **slope and intercept** of the linear relationship and also draw its **linear plot** and **scatter plot**.

**Example:**

**Input:**
X=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Y=[1, 3, 2, 5, 7, 8, 8, 9, 10, 12]

**Output:**
Slope: 1.45747126437
Intercept: -0.0586206896552
Plot:
![Screenshot (164)](https://user-images.githubusercontent.com/116869015/223514995-7a2b522a-ed8c-4253-a4f2-d25d40b3832f.png)

**Hints:** scikit-learn

**Comment by aadityavvij** [comment]
Please assign this issue to me
