### ISSUE TITLE
Convert Sorted Array to Binary Search Tree

### ISSUE THREAD

**Issue by Clucthe** [PEC-CSS/graveyard#22]
# DSA
Given an integer array nums where the elements are sorted in ascending order, convert it to a 
height-balanced
 binary search tree.

 

Example 1:

Input: nums = [-10,-3,0,5,9]
Output: [0,-3,9,-10,null,5]
Explanation: [0,-10,5,null,-3,null,9] is also accepted:

Example 2:

Input: nums = [1,3]
Output: [3,1]
Explanation: [1,null,3] and [3,1] are both height-balanced BSTs.
 

Constraints:

1.  1 <= nums.length <= 104
2.  -104 <= nums[i] <= 104
nums is sorted in a strictly increasing order.

**Comment by RohanMalik2710** [comment]
Please assign this issue to me !

**Comment by RohanMalik2710** [comment]
Thanku sir for assigning the issue !

**Comment by harshjohar** [comment]
You are already assigned @RohanMalik2710
