### ISSUE TITLE
Can he Play ?

### ISSUE THREAD

**Issue by abhinavmalhotra01** [PEC-CSS/graveyard#232]
# CP

## Problem Statement
In a lesser known football tournament , there are N players playing the game. Since, every game is bound by rules , so , when a player commits and offense , that player will receive a yellow card or a red card .
A player who satisfies one of the following conditions will be removed from the game :
* `Accumulates 2 yellow cards`
* `Receives a red card`
Once a player is removed , that player will no longer receive any card. Initially, all players have not received any cards.

There will be Q events , correctly answer the questions asked in the event.
There are 3 kinds of events in the format `c x` , described as :
* `1 x` -> player x receives yellow card
* `2 x` -> player x receives red card
* `3 x` -> you are asked to tell whether player s has been removed or not ? -> `Yes` if removed and `No` if not.

### Input Format -
N Q  ( number of players , no of events )
event1 
event2 
.....
eventQ

each event is of the type `1 x` , `2 x` , `3  x` 

### Output Format -
Print the X lines ,( X denotes the number of times event 3 occured) , the corresponding ith line should contain `Yes` or `No`

### Constraints -
1 <= N <= 100
1 <= Q <= 100
1 <= X <= N

### Example - 
Input :
3 9
3 1 
3 2 
1 2
2 1
3 1
3 2 
1 2
3 2
3 3

Output :
No
No
Yes
No
Yes
No

### Explanation:
Try to illustrate the game on pen-paper and events occuring in chronological order.

**Comment by ItsPranavz** [comment]
Please assign this to me.

**Comment by abhinavmalhotra01** [comment]
> Please assign this to me.

Done ✅

**Comment by thapliyalaryan003** [comment]
Please assign this to me

**Comment by thapliyalaryan003** [comment]
Please assign this to me

**Comment by thapliyalaryan003** [comment]
Please assign this to me.

**Comment by abhinavmalhotra01** [comment]
> Please assign this to me.

Vro don't spam 🥲 usne pehle comment kra tha

**Comment by thapliyalaryan003** [comment]
Please assign this to me.

**Comment by thapliyalaryan003** [comment]
Network error tha sir send nhi ho rha tha islie multiple baar ho gya

**Comment by abhinavmalhotra01** [comment]
> Network error tha sir send nhi ho rha tha islie multiple baar ho gya

Np 📈
