### ISSUE TITLE
Write JS code for greeting users

### ISSUE THREAD

**Issue by ugpec79** [PEC-CSS/graveyard#28]
<h1>JS</h1>
Take the input of username from user via browser and then greet them either via alert or by showing it on browser's window

**Comment by Dharya4242** [comment]
Please assign this issue to me.

**Comment by harshjohar** [comment]
goodluck @Dharyaj11

**Comment by ken1000minus7** [comment]
Unassigning cuz uk why

**Comment by Dharya4242** [comment]
Sir Please assign this issue to me again , this time I will do it .

**Comment by ken1000minus7** [comment]
Complete #23 first

**Comment by hattymatty1** [comment]
Please assign this issue to me...

**Comment by Dharya4242** [comment]
> Complete #23 first

Completed sir

**Comment by ken1000minus7** [comment]
Hmm much confusions, chalo assigning @Dharyaj11
