### ISSUE TITLE
Divide the array into two sub-arrays

### ISSUE THREAD

**Issue by DhruvGoyal375** [PEC-CSS/graveyard#3]
# ml
arrayOne - 
[[10 12 14]
[16 18 20]
[22 24 26]
[28 30 32]]

Divide arrayOne into two sub-arrays using numpy.split().
Expected Output -
[array([[10, 12, 14],[16, 18, 20]]),
array([[22, 24, 26],[28, 30, 32]])]

**Comment by himanshusab12** [comment]
Please assign this issue to me
