### ISSUE TITLE
Make a Dice Roll

### ISSUE THREAD

**Issue by ugpec79** [PEC-CSS/graveyard#30]
<h1>JS</h1>
Using the floor and random function of Math library in JS, Show a random digit ranging from 1 to 6 through alert on every click on the button created on a webpage

**Comment by ItsPranavz** [comment]
Please assign this issue to me.

**Comment by ken1000minus7** [comment]
Work on one issue at a time :redeyes:

**Comment by ken1000minus7** [comment]
@ItsPranavz wanna work on this now?

**Comment by RohanMalik2710** [comment]
_If no one else is in for it,_ **Please assign this issue to me**

**Comment by ken1000minus7** [comment]
Sure

**Comment by ken1000minus7** [comment]
Wait u already hv an issue assigned finish that first

**Comment by RohanMalik2710** [comment]
I will finish that issue and then get back to you
