### ISSUE TITLE
Write a JS Program for following problem

### ISSUE THREAD

**Issue by ugpec79** [PEC-CSS/graveyard#32]
<h1>JS</h1>
You need to create temperature convertor, the temperature should be converted from Fahrenheit to Celsius and vice versa. 
Optional: Make the convertor for Kelvin to Celsius and Fahrenheit to Kelvin and Vice Versa also

**Comment by aadityavvij** [comment]
Please assign this issue to me

**Comment by Modernbeast02** [comment]
> Please assign this issue to me

Solve previous issue first :redeyes:

**Comment by krittika2004** [comment]
please assign this issue to me

**Comment by aadityavvij** [comment]
Solved previous issues
Now, please assign it to me

**Comment by hattymatty1** [comment]
Please assign this issue to me :)

**Comment by ken1000minus7** [comment]
Sure, gl
