### ISSUE TITLE
Find the positions where elements of two arrays match

### ISSUE THREAD

**Issue by DhruvGoyal375** [PEC-CSS/graveyard#4]
# ml
arrayOne = np.array([1,2,3,2,3,4,3,4,5,6])
arrayTwo = np.array([7,2,10,2,7,4,9,4,9,8])
a. Find the positions where elements of arrayOne and arrayTwo match using numpy.where().
b. Join arrayOne and arrayTwo using numpy.concatenate() .

**Comment by aadityavvij** [comment]
Please assign this to me

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by AkankshaNarula** [comment]
Pls assign this issue to me

**Comment by ken1000minus7** [comment]
@aadityavvij @himanshusab12 u both hv pending prs, please resolve them before asking for more issues
@AkankshaNarula assigning you
