### ISSUE TITLE
Solve "Love For Cricket"

### ISSUE THREAD

**Issue by Ishwarendra** [PEC-CSS/graveyard#45]
# CP
The problem statement is given [here](https://www.hackerrank.com/contests/codecode-pec/challenges/love-for-cricket). Go ahead and write code for this and submit it as well.

Share screenshot showing all testcases or not. PR will be merged only if all testcases pass.

**Comment by AkankshaNarula** [comment]
sir pls assign this issue to me

**Comment by Ishwarendra** [comment]
@AkankshaNarula I assigned you #26. You can work on that instead of this one.

**Comment by AkankshaNarula** [comment]
ok sir ty

**Comment by devikasood** [comment]
sir please assign

**Comment by himanshusab12** [comment]
Sir please assign this issueto me

**Comment by Ishwarendra** [comment]
Assigned @devikasood. Sorry @himanshusab12 first come first serve basis.

<details>

<summary>unless</summary>
This is your first PR and the one who commented before has already made PR(s). In that case, depending on time gap of comment we will decide who to assign issue.
</details>
