### ISSUE TITLE
Solve "Floor and Ceil"

### ISSUE THREAD

**Issue by Ishwarendra** [PEC-CSS/graveyard#46]
# CP 
Problem Link: https://www.hackerrank.com/contests/testing-1669399991/challenges/floor-and-ceil-1-1

- Attach screenshot showing all testcases passed. PR will be merged only if all testcases are passed.

**Comment by himanshusab12** [comment]
Sir, it is showing error when i am opening the link

**Comment by GauravGupta993** [comment]
I have solved this question and all test cases are passed. But I am already assigned another issue. Shall I create a PR?

**Comment by Ishwarendra** [comment]
Can you attach screenshot of error @himanshusab12

**Comment by himanshusab12** [comment]
![image](https://user-images.githubusercontent.com/119474384/222358413-59ba3bb0-3220-499c-8417-b1f5e215d04c.png)

**Comment by Ishwarendra** [comment]
@himanshusab12 Register for the contest first.
contest link if you are unable to find it: https://www.hackerrank.com/testing-1669399991
