### ISSUE TITLE
Given 2 numpy arrays return unique elements

### ISSUE THREAD

**Issue by abhinavmalhotra01** [PEC-CSS/graveyard#52]
# ML

Compare the elements at same index in array1 and array2 , if they dont match , append the array1 element to the output array

### Example
array1 = np.array([1,2,3,4,5,6,7])
array2 = np.array([3,2,3,8,6,6,7])

the output array should be ([1,4,5]) 
explanation : at index 0 , array1 and array2 have different elements , append the element of the first array;

**Comment by aadityavvij** [comment]
Please assign this issue to me
