### ISSUE TITLE
Numbers between a given range

### ISSUE THREAD

**Issue by abhinavmalhotra01** [PEC-CSS/graveyard#53]
# ML

Given a numpy array and 2 integers l,r ; 
return an array consisting of all the array elements that fall in the [l,r] range

### Example 
l=2 , r=5 ; arr1 = np.array([1,2,3,4,5,6])

output array -> array([2,3,4,5])

**Comment by AkankshaNarula** [comment]
Pls assign me this issue

**Comment by aadityavvij** [comment]
Please assign this issue to me

**Comment by ziqIshika0503** [comment]
please assign this issue to me

**Comment by abhinavmalhotra01** [comment]
@aadityavvij you can first work on #52
