### ISSUE TITLE
Return the count of occurences of a number in array

### ISSUE THREAD

**Issue by abhinavmalhotra01** [PEC-CSS/graveyard#54]
# ML

Given an integer num and a numpy array , return the number of times num appears in the array

### Example 
array1 = np.array([1,2,3,2,1,3,2]) and num =1 
output : 2 
explanation : 1 appears twice in the array at indices 0,4 ;

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by ken1000minus7** [comment]
Gl
