### ISSUE TITLE
Create a DataFrame birds from the dictionary data

### ISSUE THREAD

**Issue by SUGAM-ARORA** [PEC-CSS/graveyard#56]
### **ML**

data = {
'birds': ['Cranes', 'Cranes', 'plovers', 'spoonbills', 'spoonbills', 'Cranes', 'plovers', 'Cranes', 'spoonbills', 'spoonbills'],
'age': [3.5, 4, 1.5, np.nan, 6, 3, 5.5, np.nan, 8, 4],
'visits': [2, 4, 3, 4, 3, 4, 2, 2, 3, 2],
'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Create a DataFrame birds from this dictionary data which has the index labels.

**Comment by AkankshaNarula** [comment]
Pls assign me this issue

**Comment by AkankshaNarula** [comment]
Pls assign me this issue

**Comment by NandiniGera** [comment]
> Pls assign me this issue

done

**Comment by NandiniGera** [comment]
> Pls assign me this issue

Complete the already assigned issue first, will assign you this after that.

**Comment by AkankshaNarula** [comment]
Kindly assign me this issue again now
