### ISSUE TITLE
Create matrix and access rows and columns

### ISSUE THREAD

**Issue by SUGAM-ARORA** [PEC-CSS/graveyard#59]
### ML
------------------------------------------

(a) Create a 4x5 array of even numbers: 10, 12, 14, …
(b) Extract third column
(c) Set the fourth row to 1,2,3,4,5

Note: there are many ways to achieve this.

**Comment by ItsPranavz** [comment]
Any specific languages to use or libraries like numpy?

**Comment by SUGAM-ARORA** [comment]
numpy

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by ziqIshika0503** [comment]
please assign this issue to me
