### ISSUE TITLE
Create city dataframe

### ISSUE THREAD

**Issue by SUGAM-ARORA** [PEC-CSS/graveyard#61]
### ML
-------------------------------
Create another numpy matrix and a data frame about cities in a similar fashion: create a matrix of data, and create a data frame from it using pd.DataFrame. Specify index (row names) and columns (variable names). Include at least 3 cities and 3 variables (e.g. population in millions, size in km2, and population density people per km2).

Hint: you may invent both city names and the figures!

**Comment by ItsPranavz** [comment]
Please assign this to me.

**Comment by ken1000minus7** [comment]
Sure, gl
