### ISSUE TITLE
Crime against women

### ISSUE THREAD

**Issue by SUGAM-ARORA** [PEC-CSS/graveyard#62]
ML
-----------------------
Kaggle dataset : https://www.kaggle.com/datasets/greeshmagirish/crime-against-women-20012014-india
----------------------
Which state has featured in both the lists of "Maximum number of rape cases" and "Maximum number of Importation cases"?

**Comment by aadityavvij** [comment]
Please assign this issue to me

**Comment by Ishwarendra** [comment]
You already have two issues assigned @aadityavvij. Get them merged before taking up any new issues
