### ISSUE TITLE
Remove all duplicates

### ISSUE THREAD

**Issue by RISHABH2407** [PEC-CSS/graveyard#65]
# DSA
A string will be given which may contain lowercase and uppercase characters, so the goal is to remove duplicates, and the order of characters in the output should be the same as in the given string 
Expected Time Complexity: O(N)
Expected Auxiliary Space: O(N)

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by ragss69** [comment]
Please assign this issue to me

**Comment by AkankshaNarula** [comment]
Pls assign this issue to me

**Comment by ken1000minus7** [comment]
@himanshusab12 u already hv 4 prs pending resolve them first
@ragss69 assigning u on fcfs basis
