### ISSUE TITLE
If Strings are rotated 

### ISSUE THREAD

**Issue by RISHABH2407** [PEC-CSS/graveyard#66]
Two strings are given and we have to check if they are rotation of each other or not. 
Expected Time Complexity: O(1).
Expected Space Complexity: O(N)

**Comment by Abhishek-Sood** [comment]
please assign it to me

**Comment by Ishwarendra** [comment]
Assigned @Abhishek-Sood

**Comment by harshjohar** [comment]
@Abhishek-Sood any updates?

**Comment by Abhishek-Sood** [comment]
yes sir uploading
