### ISSUE TITLE
Combining of NumPy Arrays

### ISSUE THREAD

**Issue by sparsh44** [PEC-CSS/graveyard#67]
**arr1 = np.array([1,2,3,4,5,6,7,8])
arr2 = np.array([1,2,3,4], [10,9,8,7])**

Write a program to join/stack the two numpy arrays :   
a.) Stack the arrays vertically -> Output should be of dimension : 2X8
b.) Stack the arrays horizontally -> Output should be of dimension : 8X2

Note : Reshape the arrays accordingly.

**Comment by aadityavvij** [comment]
Please assign this issue to me

**Comment by sparsh44** [comment]
You have to wait for assignment of issue...
Then only you should push the code.

**Comment by sparsh44** [comment]
Good job

**Comment by aadityavvij** [comment]
Thanks sir, will wait for the assignment in future
