### ISSUE TITLE
Beginning of Plots!!

### ISSUE THREAD

**Issue by sparsh44** [PEC-CSS/graveyard#69]
Given 2 datas :

x = np.array([10,20,30,40,50,60,77])
y = np.array([100,20,1,19,22,22,22]) 

Plot the points (x,y) using Matplotlib library:

a.) scatter
b.)plot
c.)step (Note : **Draw Vertical Lines from point to x axis as well**)
d.)stem

Note : Use color, marker, linestyle, linewidth  attributes to beautify the plot...

**Label  X axis as 'X axis' & Label Y axis as 'Y axis'**

Submit a **.ipynb** file

**Comment by ItsPranavz** [comment]
Please assign this to me.
