### ISSUE TITLE
Write HTML/CSS and replicate the given target image in the least code possible

### ISSUE THREAD

**Issue by harshshukla07** [PEC-CSS/graveyard#7]
#CSS
![13](https://user-images.githubusercontent.com/107511647/221370668-615fb3f8-e811-4706-9442-c55407b45001.png)

<div></div>
<style>
  div {
    width: 100px;
    height: 100px;
    background: #dd6b4d;
  }
</style>

**Comment by Abhishek-Sood** [comment]
please assign it to me

**Comment by ken1000minus7** [comment]
Unassigning cuz- , well uk the drill

**Comment by Abhishek-Sood** [comment]
lol

**Comment by Abhishek-Sood** [comment]
yup :crycatok:

**Comment by AkankshaNarula** [comment]
Pls assign this issue to me
