### ISSUE TITLE
Tour of King

### ISSUE THREAD

**Issue by harshshukla07** [PEC-CSS/graveyard#71]
# CP

King loves to go on tours with his friends.

King has N cars that can seat 5 people each and M cars that can seat 7 people each. Determine the maximum number of people that can travel together in these cars.

INPUT FORMAT:
The first line of input contains a single integer T, the number of test cases.
The first and only line of each test case contains two space-separated integers N and M — the number of 5-seaters and 7-seaters, respectively.

OUTPUT FORMAT:
For each test case, output on a new line the maximum number of people that can travel together.

CONSTRAINTS:
1≤T≤100
0≤N,M≤100

SAMPLE:
Input
4
4 8
2 13
14 5
8 8

Output
76
101
105
96

**Comment by hattymatty1** [comment]
Please assign this issue to me

**Comment by Ishwarendra** [comment]
Assigned @hattymatty1
