### ISSUE TITLE
Ageing

### ISSUE THREAD

**Issue by harshshukla07** [PEC-CSS/graveyard#72]
# CP

Johar's current age is 20 years, while Ishwar's current age is 10 years.
Determine Ishwar's age when Johar will be X years old.

Note: Assume that Johar and Ishwar were born on same day and same month (just different year).

INPUT FORMAT:
The first line of input will contain a single integer T, denoting the number of test cases.
Each test case consists of a single integer X, the age of Johar.

OUTPUT FORMAT:
For each test case, output Ishwar's age when Johar will be X years old.

CONSTRAINTS:
1≤T≤25
25≤X≤50

SAMPLE:
INPUT
4
25
36
50
44

OUTPUT
15
26
40
34

**Comment by krittika2004** [comment]
please assign this issue to me

**Comment by Ishwarendra** [comment]
Assigned @krittika2004

**Comment by harshjohar** [comment]
@krittika2004 any updates?

**Comment by GauravGupta993** [comment]
is it fine to for me create PR for this issue since it is inactive for some time?

**Comment by krittika2004** [comment]
No i will be creating pr today..i was away for sometime

**Comment by GauravGupta993** [comment]
> No i will be creating pr today..i was away for sometime

Sorry, my bad
