### ISSUE TITLE
first and last occurrence of x 

### ISSUE THREAD

**Issue by RISHABH2407** [PEC-CSS/graveyard#73]
# DSA
A sorted array and a long x will be given and you need to find the first and last occurrence of x, and put them in a Long ArrayList and return. If x is not found in the array put -1 for both left and right. 

n=9, x=5
arr[] = { 1, 3, 5, 5, 5, 5, 67, 123, 125 }
Output:  2 5
Explanation: The first occurrence of 5 is at index 2 and last
             occurrence of 5 is at index 5. 

Expected Time Complexity: O(logN)
Expected Auxiliary Space: O(1)

**Comment by himanshusab12** [comment]
Please  assign this issue to me

**Comment by Ishwarendra** [comment]
Assigned @himanshusab12
