### ISSUE TITLE
Basic Recurssion problem

### ISSUE THREAD

**Issue by Garv085** [PEC-CSS/graveyard#8]
Simran is running up a staircase with N steps, and can hop(jump) either 1 step, 2 steps or 3 steps at a time. You have to count, how many possible ways Simran can run up to the stairs.
Input Format:
Input contains integer N that is number of steps
Output Format:
Output for each integer N the no of possible ways w. 
Constraints:
1≤N≤30
SAMPLE INPUT: 4
SAMPLE OUTPUT: 7

**Comment by aadityavvij** [comment]
Please assign this to me
