### ISSUE TITLE
Find in Mountain Array. 

### ISSUE THREAD

**Issue by si-ddhant** [PEC-CSS/graveyard#84]
You may recall that an array arr is a mountain array if and only if:

1) arr.length >= 3
2)There exists some i with 0 < i < arr.length - 1 such that:
     a) arr[0] < arr[1] < ... < arr[i - 1] < arr[i]
     b) arr[i] > arr[i + 1] > ... > arr[arr.length - 1]

Given a mountain array mountainArr, return the minimum index such that mountainArr.get(index) == target. If such an index does not exist, return -1.

[leetcode link](https://leetcode.com/problems/find-in-mountain-array/)

**Comment by ragss69** [comment]
Please assign this issue to me

**Comment by si-ddhant** [comment]
> Please assign this issue to me

pls complete your work on the previously assigned issue.

**Comment by Prajwa-l-Kumar** [comment]
Please assign this issue to me

**Comment by SambhavJain74** [comment]
Solution accepted on Leetcode
Edit: Didn't notice its already assigned.

**Comment by si-ddhant** [comment]
> Solution accepted on Leetcode Edit: Didn't notice its already assigned.

Well done atleast you solved another DSA problem. 😎
