### ISSUE TITLE
minimum add to make a parentheses valid

### ISSUE THREAD

**Issue by si-ddhant** [PEC-CSS/graveyard#87]
# DSA
A parentheses string is valid if and only if:

1) It is the empty string,
2) It can be written as AB (A concatenated with B), where A and B are valid strings, or
3) It can be written as (A), where A is a valid string.

You are given a parentheses string s. In one move, you can insert a parenthesis at any position of the string.

For example, if s = "()))", you can insert an opening parenthesis to be "(()))" or a closing parenthesis to be "())))".
                                   Return the minimum number of moves required to make s valid.

 [leetcode link](https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/)
add ss if accepted.

**Comment by ParasBisht2003** [comment]
please assign this issue to me
