### ISSUE TITLE
Capacity to ship packages within D days.

### ISSUE THREAD

**Issue by si-ddhant** [PEC-CSS/graveyard#88]
A conveyor belt has packages that must be shipped from one port to another within days` days`.

The `ith` package on the conveyor belt has a weight of `weights[i]`. Each day, we load the ship with packages on the conveyor belt (in the order given by `weights`). We may not load more weight than the maximum weight capacity of the ship.

Return the least weight capacity of the ship that will result in all the packages on the conveyor belt being shipped within `days` days.

 [leetcode link](https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/)

**Comment by himanshusab12** [comment]
Please assign this issue to me

**Comment by si-ddhant** [comment]
> Please assign this issue to me

you are already assigned to some issues.

**Comment by ParasBisht2003** [comment]
please assign this issue to me

**Comment by si-ddhant** [comment]
assigned
