### ISSUE TITLE
Minimum absolute difference

### ISSUE THREAD

**Issue by si-ddhant** [PEC-CSS/graveyard#90]
Given an array of distinct integers `arr`, find all pairs of elements with the minimum absolute difference of any two elements.

Return a list of pairs in ascending order(with respect to pairs), each pair `[a, b]` follows

1) `a, b` are from `arr`
2) `a < b`
3) `b - a` equals to the minimum absolute difference of any two elements in `arr`

[leetcode link](https://leetcode.com/problems/minimum-absolute-difference/)

**Comment by hattymatty1** [comment]
Please assign this issue to me.

**Comment by si-ddhant** [comment]
@hattymatty1 please don't make a single pull request for both the issues. try creating different branches for different issues.
