### ISSUE TITLE
Coronavirus Spread

### ISSUE THREAD

**Issue by harshshukla07** [PEC-CSS/graveyard#95]
#CP

There are N people on a street (numbered 1 through N). For simplicity, we'll view them as points on a line. For each valid i, the position of the i-th person is Xi .

It turns out that exactly one of these people is infected with the virus COVID-19, but we do not know which one. The virus will spread from an infected person to a non-infected person whenever the distance between them is at most 2. If we wait long enough, a specific set of people (depending on the person that was infected initially) will become infected; let's call the size of this set the final number of infected people.

Your task is to find the smallest and largest value of the final number of infected people, i.e. this number in the best and in the worst possible scenario.

INPUT:
The first line of the input contains a single integer T denoting the number of test cases. The description of T test cases follows.
The first line of each test case contains a single integer N.
The second line contains N space-seperated integers X1,X2,…,XN.

OUTPUT:
For each test case, print a single line containing two space-separated integers ― the minimum and maximum possible final number of infected people.

CONSTRAINTS:
1≤T≤2,000
2≤N≤8
0≤Xi≤10 for each valid i
X1<X2<…<XN.

SAMPLE:
INPUT
3
2
3 6
3
1 3 5
5
1 2 5 6 7

OUTPUT
1 1
3 3
2 3

**Comment by aadityavvij** [comment]
Please assign this issue to me

**Comment by ken1000minus7** [comment]
Unassigning, you still have two prs pending

**Comment by devikasood** [comment]
please assign this issue to me

**Comment by GauravGupta993** [comment]
is it fine for me to create PR for this issue since this is inactive for some time?

**Comment by devikasood** [comment]
hello Gaurav, please don't.. I was inactive for a while, but now im almost done with this issue, I will create pr by tomorrow.

**Comment by GauravGupta993** [comment]
> hello Gaurav, please don't.. I was inactive for a while, but now im almost done with this issue, I will create pr by tomorrow.

Ok sorry, my bad

**Comment by Ishwarendra** [comment]
Any updates @devikasood

**Comment by devikasood** [comment]
pr created..
sorry for taking so long
