### ISSUE TITLE
Heart-Failure

### ISSUE THREAD

**Issue by SUGAM-ARORA** [PEC-CSS/graveyard#96]
**ML**
----------------------------------

Kaggle data set
----------------------------------
https://www.kaggle.com/datasets/andrewmvd/heart-failure-clinical-data

Identify 
(a)Number of Patients with Abnormal Sodium level in the blood
(b)Number of Patients with Smoking Habit
(c)Number of Patients died during follow-up period

**Comment by aadityavvij** [comment]
Please assign this issue to me

**Comment by NandiniGera** [comment]
> Please assign this issue to me

done, and complete #52 first

**Comment by dhruvsingal24** [comment]
please assign this issue to me

**Comment by uttammittal02** [comment]
Assigned it to you @dhruvsingal24

**Comment by Abhishek-Sood** [comment]
is someone doing this???if no can u assign it to me :)

**Comment by dhruvsingal24** [comment]
i am doing this

**Comment by Abhishek-Sood** [comment]
> i am doing this
sure sry sry :)

**Comment by dhruvsingal24** [comment]
I will try to solve it by tomorrow 1 pm. If i am not able to you can have it

**Comment by dhruvsingal24** [comment]
I will unassign it

**Comment by Abhishek-Sood** [comment]
so whos take is it ?????

**Comment by harshjohar** [comment]
@Abhishek-Sood you can do this one
