### ISSUE TITLE
Create a sequence of -1 , 1

### ISSUE THREAD

**Issue by SUGAM-ARORA** [PEC-CSS/graveyard#97]
We can describe a coin toss as Binomial(1, 0.5) where 1 refers to the fact that we toss a single coin, and 0.5 means it has probability 0.5 to come heads up. So such random variables are sequences of zeros and ones. But how can we get a sequence of -1 and 1 instead?

**Comment by thapliyalaryan003** [comment]
Please assign this to me.(Can I make random variable a function with if and else)

**Comment by SUGAM-ARORA** [comment]
your code is absolutely correct but for easier way we can use
: 2*np.random.binomial(1, 0.5, size=10) - 1
just one line code

**Comment by thapliyalaryan003** [comment]
Thankyou sir will try to improve in next issue.
